#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor HDMI-0 -d I II III IV V
bspc monitor DP-0 -d VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          6

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config single_monocle   true
bspc config gapless_monocle      true

bspc config pointer_modifier super
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
bash ~/.screenlayout/standard.sh &
killall polybar; polybar primary & polybar secondary &
start-pulseaudio-x11 &
killall pa-applet; pa-applet &
killall nm-applet; nm-applet &
killall xfce4-power-manager; xfce4-power-manager &
dropbox &
killall pamac-tray; pamac-tray &
nitrogen --restore; sleep 1; compton -b &
